services:
  hello:
    image: docker.io/library/nginx:latest
    container_name: hello
    networks:
      homelabnetwork:
        ipv4_address: 192.168.4.100
    restart: unless-stopped

networks:
  homelabnetwork:
    name: homelabnetwork
    external: true
    