---
- name: Check if AWS CLI is installed
  ansible.builtin.command: aws --version
  register: cli_tools_aws_cli_version
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Download AWS CLI archive
  ansible.builtin.get_url:
    url: "{{ cli_tools_aws_cli_url }}"
    dest: /tmp/awscliv2.zip
    mode: '0644'
  when: cli_tools_aws_cli_version.stdout is not defined or "aws-cli/2" not in cli_tools_aws_cli_version.stdout

- name: Unzip AWS CLI
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
    creates: /tmp/aws/install
  when: cli_tools_aws_cli_version.stdout is not defined or "aws-cli/2" not in cli_tools_aws_cli_version.stdout

- name: Install AWS CLI
  ansible.builtin.command: ./aws/install --update
  args:
    chdir: /tmp
  become: true
  when: cli_tools_aws_cli_version.stdout is not defined or "aws-cli/2" not in cli_tools_aws_cli_version.stdout

- name: Clean up AWS CLI temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/aws
    - /tmp/awscliv2.zip
  when: cli_tools_aws_cli_version.stdout is not defined or "aws-cli/2" not in cli_tools_aws_cli_version.stdout
