---
- name: Check if Dapr CLI is installed
  ansible.builtin.command: which dapr
  register: cli_tools_dapr_cli_check
  ignore_errors: true
  changed_when: false

- name: Download Dapr CLI installer
  ansible.builtin.uri:
    url: "{{ cli_tools_dapr_cli_install_url }}"
    dest: /tmp/dapr-installer.sh
    method: GET
    return_content: false
    status_code: 200
  when: cli_tools_dapr_cli_check.rc != 0

- name: Install Dapr CLI
  ansible.builtin.shell: |
    set -o pipefail
    /bin/bash /tmp/dapr-installer.sh
  args:
    executable: /bin/bash
  when: cli_tools_dapr_cli_check.rc != 0
  changed_when: false
