---

- name: Ansible Tooling
  ansible.builtin.import_tasks: ansible-tooling.yml
  ignore_errors: true

- name: Install Dapr CLI
  ansible.builtin.import_tasks: dapr.yml
  ignore_errors: true

- name: Install cfssl
  ansible.builtin.import_tasks: cfssl.yml
  ignore_errors: true

- name: Install AWS CLI
  ansible.builtin.import_tasks: aws.yml
  ignore_errors: true

- name: Install LocalStack CLI
  ansible.builtin.import_tasks: localstack.yml
  ignore_errors: true

- name: Install Tilt
  ansible.builtin.import_tasks: tilt.yml
  ignore_errors: true

- name: Install Go
  ansible.builtin.import_tasks: go-lang.yml
  ignore_errors: false

- name: Install PowerShell
  ansible.builtin.import_tasks: powershell.yml
  ignore_errors: false

- name: Install Terraform
  ansible.builtin.import_tasks: terraform.yml
  ignore_errors: false

- name: Install NVM
  ansible.builtin.import_tasks: nvm.yml
  ignore_errors: false

- name: Install Quarkus CLI
  ansible.builtin.import_tasks: quarkus.yml
  ignore_errors: false

- name: Install Starship
  ansible.builtin.import_tasks: starship.yml
  ignore_errors: false