

- name: Add HashiCorp repo for Terraform
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: '0644'


- name: Install Terraform
  ansible.builtin.dnf:
    name: terraform
    state: present
