---
- name: Install cloud-provider-kind
  ansible.builtin.shell: |
    go install sigs.k8s.io/cloud-provider-kind@latest
  args:
    creates: "usr/local/go/bin/cloud-provider-kind"
  environment:
    GOBIN: "{{ ansible_env.HOME }}/.local/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

  become: false
