---
- name: Check if Helm is installed
  ansible.builtin.command: which helm
  register: helm_check
  ignore_errors: true
  changed_when: false

- name: Install Helm
  ansible.builtin.package:
    name: helm
    state: present
  become: true
  when: helm_check.rc != 0
