

---
- name: Check if K9s is already installed
  ansible.builtin.command: which k9s
  register: k9s_check
  changed_when: false
  ignore_errors: true

- name: Download latest K9s tarball
  ansible.builtin.get_url:
    url: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz
    dest: /tmp/k9s.tar.gz
    mode: '0644'
  when: k9s_check.rc != 0

- name: Create temporary K9s extraction directory
  ansible.builtin.file:
    path: /tmp/k9s
    state: directory
    mode: '0755'
  when: k9s_check.rc != 0

- name: Extract K9s binary
  ansible.builtin.unarchive:
    src: /tmp/k9s.tar.gz
    dest: /tmp/k9s
    remote_src: true
    creates: /tmp/k9s/k9s
  when: k9s_check.rc != 0


- name: Move K9s binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/k9s/k9s
    dest: /usr/local/bin/k9s
    mode: '0755'
    remote_src: true
  become: true
  when: k9s_check.rc != 0

- name: Clean up K9s temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/k9s.tar.gz
    - /tmp/k9s
  when: k9s_check.rc != 0
