---
- name: Check if kind is installed
  ansible.builtin.command: which kind
  register: kind_check
  ignore_errors: true
  changed_when: false

- name: Install Kind
  ansible.builtin.shell: |
    # For AMD64 / x86_64
    [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
    # For ARM64
    [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-arm64
    chmod +x ./kind
    sudo mv ./kind /usr/local/bin/kind
  when: kind_check.rc != 0
  become: true
