---
- import_tasks: kubectl.yml

- import_tasks: helm.yml

- import_tasks: kubectx.yml

- import_tasks: kind.yml

- import_tasks: k9s.yml

- import_tasks: cloud_provider_kind.yml
  ignore_errors: true

- import_tasks: tekton.yml
  ignore_errors: false

- import_tasks: argocd.yml
  ignore_errors: true

- import_tasks: istio.yml
  ignore_errors: true
