---
- name: Configure Fedora Workstation
  hosts: localhost
  become: false

  roles:
    - role: base_packages
      become: true

    - role: flatpak_apps
      become: true

    - role: cli_tools
      become: true

    - role: cockpit_setup
      become: true

    - role: kubernetes_tools
      become: false

    - role: podman
      become: true
